//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXE.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Company.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All interactions on our platform are secure and confidential, giving you peace of mind that your data and conversations are protected..
        /// </summary>
        public static string All_interactions {
            get {
                return ResourceManager.GetString("All interactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All interactions on our platform are secure and confidential, giving you peace of mind that your data and conversations are protected..
        /// </summary>
        public static string Allinteractions {
            get {
                return ResourceManager.GetString("Allinteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Interpretercom, we believe that communication should never be a barrier. That’s why we’ve created a user-friendly platform where clients can easily find and hire certified interpreters with expertise in various industries, including legal, medical, business, and more..
        /// </summary>
        public static string AtInterpretercom {
            get {
                return ResourceManager.GetString("AtInterpretercom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Home.
        /// </summary>
        public static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Appointment.
        /// </summary>
        public static string BookAppointment {
            get {
                return ResourceManager.GetString("BookAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core values.
        /// </summary>
        public static string Corevalues {
            get {
                return ResourceManager.GetString("Corevalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultural Respect: Promote respect and cultural understanding in all communication situations..
        /// </summary>
        public static string CulturalRespect {
            get {
                return ResourceManager.GetString("CulturalRespect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Centered: Always listen and respond to customer needs..
        /// </summary>
        public static string CustomerCentered {
            get {
                return ResourceManager.GetString("CustomerCentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized Solutions.
        /// </summary>
        public static string CustomizedSolutions {
            get {
                return ResourceManager.GetString("CustomizedSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Booking.
        /// </summary>
        public static string EasyBooking {
            get {
                return ResourceManager.GetString("EasyBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every client is unique, and so are their interpretation needs. Whether you need a one-time service or ongoing support, we tailor our solutions to your project..
        /// </summary>
        public static string Everyclient {
            get {
                return ResourceManager.GetString("Everyclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexibility and Convenience.
        /// </summary>
        public static string Flexibility {
            get {
                return ResourceManager.GetString("Flexibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From small businesses expanding into new markets to individuals needing help with personal matters, our platform is designed to be flexible, comprehensive, and tailored to the needs of our clients..
        /// </summary>
        public static string Fromsmall {
            get {
                return ResourceManager.GetString("Fromsmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Experts.
        /// </summary>
        public static string LanguageExperts {
            get {
                return ResourceManager.GetString("LanguageExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission is simple yet powerful: To enable seamless communication across languages and cultures. We strive to remove the challenges that come with language differences by offering interpretation services that meet the highest standards of accuracy, professionalism, and reliability. We are committed to fostering cross-cultural understanding and empowering businesses and individuals to connect with others worldwide..
        /// </summary>
        public static string Ourmission {
            get {
                return ResourceManager.GetString("Ourmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Process.
        /// </summary>
        public static string OurProcess {
            get {
                return ResourceManager.GetString("OurProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service.
        /// </summary>
        public static string OurService {
            get {
                return ResourceManager.GetString("OurService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team of interpreters consists of language professionals with years of experience and international certifications..
        /// </summary>
        public static string Ourteam {
            get {
                return ResourceManager.GetString("Ourteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for interpreters by language, location, or specialization. Our platform is designed to make the booking process as simple as possible, with transparent pricing and availability..
        /// </summary>
        public static string Searchfor {
            get {
                return ResourceManager.GetString("Searchfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Interpreter.
        /// </summary>
        public static string Searchinterpreter {
            get {
                return ResourceManager.GetString("Searchinterpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Communication.
        /// </summary>
        public static string SecureCommunication {
            get {
                return ResourceManager.GetString("SecureCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Quality: Committed to providing high quality, accurate and professional services..
        /// </summary>
        public static string ServiceQuality {
            get {
                return ResourceManager.GetString("ServiceQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We aim to become the leading online hub for professional interpreting services, enabling seamless communication and understanding across all languages and cultures. We strive to deliver high-quality, on-demand services tailored to the unique needs of every client..
        /// </summary>
        public static string Weaim {
            get {
                return ResourceManager.GetString("Weaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer interpreter services for a variety of languages, from commonly spoken ones such as English, French, Chinese, and Japanese to less common languages..
        /// </summary>
        public static string Weoffer {
            get {
                return ResourceManager.GetString("Weoffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Our CEO Says.
        /// </summary>
        public static string WhatOur {
            get {
                return ResourceManager.GetString("WhatOur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide Range of Languages.
        /// </summary>
        public static string WideRange {
            get {
                return ResourceManager.GetString("WideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can hire interpreters by the hour, by the day, or for a specific project depending on your needs. Our services are available 24/7..
        /// </summary>
        public static string Youcan {
            get {
                return ResourceManager.GetString("Youcan", resourceCulture);
            }
        }
    }
}
